function print_csac_statistics(csac_state, csac)
%PRINT_CSAC_STATISTICS Print gate and season statistics for one CSAC.

    fprintf('\n=== CSAC %d Final Statistics ===\n', csac);
    fprintf('UKF: %d accepted, %d rejected (%.1f%% rejection rate)\n', ...
        csac_state.gate_accept_count_ukf, csac_state.gate_reject_count_ukf, ...
        100 * csac_state.gate_reject_count_ukf / ...
        max(1, csac_state.gate_accept_count_ukf + csac_state.gate_reject_count_ukf));
    fprintf('PF:  %d accepted, %d rejected (%.1f%% rejection rate)\n', ...
        csac_state.gate_accept_count_pf, csac_state.gate_reject_count_pf, ...
        100 * csac_state.gate_reject_count_pf / ...
        max(1, csac_state.gate_accept_count_pf + csac_state.gate_reject_count_pf));
    fprintf('Season gate: %d active days, %d inactive days (%.1f%% active)\n', ...
        csac_state.season_gate_active_days, csac_state.season_gate_inactive_days, ...
        100 * csac_state.season_gate_active_days / ...
        max(1, csac_state.season_gate_active_days + csac_state.season_gate_inactive_days));
    fprintf('Heating seasons started: %d\n', csac_state.season_count);
    fprintf('=====================================\n\n');
end