function print_full_gate_summary(csac, time, house_id, ...
    is_csac_active, is_flow_ok, delta_T_ok, T_main_C, T_soil_C, flow_kg_h, alpha, filter_name)

    fprintf('%s | CSAC %d | %s | house %d | csac_active=%d | flow_ok=%d | dT_ok=%d | Tmain=%.2f | Tsoil=%.2f | flow=%.1f | alpha=%.3f\n', ...
        filter_name, csac, string(time), house_id, ...
        is_csac_active, is_flow_ok, delta_T_ok, T_main_C, T_soil_C, flow_kg_h, alpha);
end